"""Tambahkan tabel AnggotaAktivitas untuk hubungan many-to-many antara Aktivitas dan User

Revision ID: 0c23bea48aa0
Revises: 715eb5a9a9ff
Create Date: 2025-09-02 15:29:09.783206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c23bea48aa0'
down_revision: Union[str, Sequence[str], None] = '715eb5a9a9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anggota_aktivitas',
    sa.Column('aktivitas_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aktivitas_id'], ['aktivitas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('aktivitas_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anggota_aktivitas')
    # ### end Alembic commands ###
