"""Hapus cascade dari project ke aktivitas dan tambahkan ondelete

Revision ID: 0d89f28c249c
Revises: d2e3445b854c
Create Date: 2025-09-06 05:26:06.536040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d89f28c249c'
down_revision: Union[str, Sequence[str], None] = 'd2e3445b854c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('aktivitas_project_id_fkey'), 'aktivitas', type_='foreignkey')
    op.create_foreign_key(None, 'aktivitas', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aktivitas', type_='foreignkey')
    op.create_foreign_key(op.f('aktivitas_project_id_fkey'), 'aktivitas', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
