"""Add cascade delete to project and activity notifications

Revision ID: 19c1f5ce8c64
Revises: 95ab7a383668
Create Date: 2025-10-08 11:49:58.294693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c1f5ce8c64'
down_revision: Union[str, Sequence[str], None] = '95ab7a383668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifikasi_related_activity_id_fkey'), 'notifikasi', type_='foreignkey')
    op.drop_constraint(op.f('notifikasi_related_project_id_fkey'), 'notifikasi', type_='foreignkey')
    op.create_foreign_key(None, 'notifikasi', 'projects', ['related_project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifikasi', 'aktivitas', ['related_activity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifikasi', type_='foreignkey')
    op.drop_constraint(None, 'notifikasi', type_='foreignkey')
    op.create_foreign_key(op.f('notifikasi_related_project_id_fkey'), 'notifikasi', 'projects', ['related_project_id'], ['id'])
    op.create_foreign_key(op.f('notifikasi_related_activity_id_fkey'), 'notifikasi', 'aktivitas', ['related_activity_id'], ['id'])
    # ### end Alembic commands ###
