"""Add public_id to aktivitas table

Revision ID: 1ef043e9157a
Revises: b7f5ba38fa2f
Create Date: 2025-10-27 15:21:59.750951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef043e9157a'
down_revision: Union[str, Sequence[str], None] = 'b7f5ba38fa2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aktivitas', sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_aktivitas_public_id'), 'aktivitas', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aktivitas_public_id'), table_name='aktivitas')
    op.drop_column('aktivitas', 'public_id')
    # ### end Alembic commands ###
