"""Perbaikan relasi dan penghapusan cascade

Revision ID: 47eed3ad4a53
Revises: 0d89f28c249c
Create Date: 2025-09-06 05:33:38.863317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47eed3ad4a53'
down_revision: Union[str, Sequence[str], None] = '0d89f28c249c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('aktivitas_project_id_fkey'), 'aktivitas', type_='foreignkey')
    op.create_foreign_key('aktivitas_project_id_fkey', 'aktivitas', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aktivitas_project_id_fkey', 'aktivitas', type_='foreignkey')
    op.create_foreign_key(op.f('aktivitas_project_id_fkey'), 'aktivitas', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
