"""Creator user id not nullable

Revision ID: 4b4d7d412ad9
Revises: cccea5fdbf84
Create Date: 2025-08-25 18:24:13.807423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4d7d412ad9'
down_revision: Union[str, Sequence[str], None] = 'cccea5fdbf84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aktivitas', 'creator_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aktivitas', 'creator_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
