"""Add detailed user profile attributes

Revision ID: 5c434a1f5bbd
Revises: 1ef043e9157a
Create Date: 2025-11-12 07:48:34.606596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c434a1f5bbd'
down_revision: Union[str, Sequence[str], None] = '1ef043e9157a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nip', sa.String(length=18), nullable=True))
    op.add_column('users', sa.Column('nipbps', sa.String(length=9), nullable=True))
    op.add_column('users', sa.Column('gol_akhir', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('tmt_gol', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('tmt_jab', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('status_kepegawaian', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('jenis_kelamin', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('nohp', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_nip'), 'users', ['nip'], unique=True)
    op.create_index(op.f('ix_users_nipbps'), 'users', ['nipbps'], unique=True)
    op.create_index(op.f('ix_users_nohp'), 'users', ['nohp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nohp'), table_name='users')
    op.drop_index(op.f('ix_users_nipbps'), table_name='users')
    op.drop_index(op.f('ix_users_nip'), table_name='users')
    op.drop_column('users', 'nohp')
    op.drop_column('users', 'jenis_kelamin')
    op.drop_column('users', 'status_kepegawaian')
    op.drop_column('users', 'tmt_jab')
    op.drop_column('users', 'tmt_gol')
    op.drop_column('users', 'gol_akhir')
    op.drop_column('users', 'nipbps')
    op.drop_column('users', 'nip')
    # ### end Alembic commands ###
