"""add status_pengecekan to daftar_dokumen

Revision ID: 5e9b94d6ffa2
Revises: 97ddd81b12ae
Create Date: 2025-08-26 20:50:31.170061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9b94d6ffa2'
down_revision: Union[str, Sequence[str], None] = '97ddd81b12ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daftar_dokumen', sa.Column('status_pengecekan', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.drop_column('daftar_dokumen', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daftar_dokumen', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Wajib Diunggah'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('daftar_dokumen', 'status_pengecekan')
    # ### end Alembic commands ###
