"""Allow null values for aktivitas_id and project_id in dokumen table

Revision ID: 715eb5a9a9ff
Revises: bece1712a1db
Create Date: 2025-08-31 17:51:12.370124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '715eb5a9a9ff'
down_revision: Union[str, Sequence[str], None] = 'bece1712a1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dokumen', 'diunggah_pada',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('dokumen', 'aktivitas_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dokumen', 'aktivitas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dokumen', 'diunggah_pada',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
