"""add hirarchy status calendar

Revision ID: 7f1058777ebc
Revises: ce89a0706aa2
Create Date: 2025-12-07 18:50:54.434338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1058777ebc'
down_revision: Union[str, Sequence[str], None] = 'ce89a0706aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aktivitas', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('aktivitas', sa.Column('kalender_view', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('aktivitas', sa.Column('status', sa.String(length=50), server_default='Belum Selesai', nullable=False))
    op.create_index(op.f('ix_aktivitas_kalender_view'), 'aktivitas', ['kalender_view'], unique=False)
    op.create_index(op.f('ix_aktivitas_parent_id'), 'aktivitas', ['parent_id'], unique=False)
    op.create_index(op.f('ix_aktivitas_status'), 'aktivitas', ['status'], unique=False)
    op.create_foreign_key(None, 'aktivitas', 'aktivitas', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aktivitas', type_='foreignkey')
    op.drop_index(op.f('ix_aktivitas_status'), table_name='aktivitas')
    op.drop_index(op.f('ix_aktivitas_parent_id'), table_name='aktivitas')
    op.drop_index(op.f('ix_aktivitas_kalender_view'), table_name='aktivitas')
    op.drop_column('aktivitas', 'status')
    op.drop_column('aktivitas', 'kalender_view')
    op.drop_column('aktivitas', 'parent_id')
    # ### end Alembic commands ###
