"""Add notifications table

Revision ID: 95ab7a383668
Revises: 47eed3ad4a53
Create Date: 2025-10-06 11:57:27.992067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95ab7a383668'
down_revision: Union[str, Sequence[str], None] = '47eed3ad4a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.add_column('notifikasi', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('notifikasi', sa.Column('related_activity_id', sa.Integer(), nullable=True))
    op.add_column('notifikasi', sa.Column('related_project_id', sa.Integer(), nullable=True))
    op.add_column('notifikasi', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('notifikasi', sa.Column('massage', sa.Text(), nullable=True))
    op.add_column('notifikasi', sa.Column('link_to', sa.String(), nullable=True))
    op.add_column('notifikasi', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('notifikasi', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'notifikasi', 'aktivitas', ['related_activity_id'], ['id'])
    op.create_foreign_key(None, 'notifikasi', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifikasi', 'projects', ['related_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifikasi', type_='foreignkey')
    op.drop_constraint(None, 'notifikasi', type_='foreignkey')
    op.drop_constraint(None, 'notifikasi', type_='foreignkey')
    op.drop_column('notifikasi', 'created_at')
    op.drop_column('notifikasi', 'is_read')
    op.drop_column('notifikasi', 'link_to')
    op.drop_column('notifikasi', 'massage')
    op.drop_column('notifikasi', 'title')
    op.drop_column('notifikasi', 'related_project_id')
    op.drop_column('notifikasi', 'related_activity_id')
    op.drop_column('notifikasi', 'user_id')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('related_activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('massage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['related_activity_id'], ['aktivitas.id'], name=op.f('notifications_related_activity_id_fkey')),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], name=op.f('notifications_related_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###
