"""add column warna in team table

Revision ID: 97ddd81b12ae
Revises: 4b4d7d412ad9
Create Date: 2025-08-25 19:47:28.005729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ddd81b12ae'
down_revision: Union[str, Sequence[str], None] = '4b4d7d412ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('warna', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'warna')
    # ### end Alembic commands ###
