"""Refactor dokumen to one-to-many

Revision ID: 9a49ce214c24
Revises: 9a93083c4009
Create Date: 2025-11-24 19:12:41.171973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a49ce214c24'
down_revision: Union[str, Sequence[str], None] = '9a93083c4009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('daftar_dokumen_dokumen_id_fkey'), 'daftar_dokumen', type_='foreignkey')
    op.drop_column('daftar_dokumen', 'dokumen_id')
    op.add_column('dokumen', sa.Column('daftar_dokumen_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dokumen', 'daftar_dokumen', ['daftar_dokumen_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dokumen', type_='foreignkey')
    op.drop_column('dokumen', 'daftar_dokumen_id')
    op.add_column('daftar_dokumen', sa.Column('dokumen_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('daftar_dokumen_dokumen_id_fkey'), 'daftar_dokumen', 'dokumen', ['dokumen_id'], ['id'])
    # ### end Alembic commands ###
