"""Add team_role to user_team_link table

Revision ID: b7f5ba38fa2f
Revises: 19c1f5ce8c64
Create Date: 2025-10-22 09:37:15.352891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f5ba38fa2f'
down_revision: Union[str, Sequence[str], None] = '19c1f5ce8c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_team_link', sa.Column('team_role', sa.String(length=50), server_default='member', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_team_link', 'team_role')
    # ### end Alembic commands ###
