"""add table projects

Revision ID: bbb8987b933c
Revises: 5e9b94d6ffa2
Create Date: 2025-08-31 15:05:29.598999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb8987b933c'
down_revision: Union[str, Sequence[str], None] = '5e9b94d6ffa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aktivitas', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'aktivitas', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aktivitas', type_='foreignkey')
    op.drop_column('aktivitas', 'project_id')
    # ### end Alembic commands ###
