"""add column project_id in dokumens table

Revision ID: bece1712a1db
Revises: bbb8987b933c
Create Date: 2025-08-31 17:13:40.767054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bece1712a1db'
down_revision: Union[str, Sequence[str], None] = 'bbb8987b933c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dokumen', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dokumen', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dokumen', type_='foreignkey')
    op.drop_column('dokumen', 'project_id')
    # ### end Alembic commands ###
