"""Create initial tables

Revision ID: cccea5fdbf84
Revises: 
Create Date: 2025-08-25 18:14:50.068648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cccea5fdbf84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_aktivitas_id'), 'aktivitas', ['id'], unique=False)
    op.create_index(op.f('ix_aktivitas_nama_aktivitas'), 'aktivitas', ['nama_aktivitas'], unique=False)
    op.drop_constraint(op.f('aktivitas_creator_user_id_fkey'), 'aktivitas', type_='foreignkey')
    op.drop_constraint(op.f('aktivitas_team_id_fkey'), 'aktivitas', type_='foreignkey')
    op.create_foreign_key(None, 'aktivitas', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'aktivitas', 'users', ['creator_user_id'], ['id'])
    op.create_index(op.f('ix_daftar_dokumen_id'), 'daftar_dokumen', ['id'], unique=False)
    op.drop_constraint(op.f('fk_aktivitas'), 'daftar_dokumen', type_='foreignkey')
    op.drop_constraint(op.f('fk_dokumen_fisik'), 'daftar_dokumen', type_='foreignkey')
    op.create_foreign_key(None, 'daftar_dokumen', 'aktivitas', ['aktivitas_id'], ['id'])
    op.create_foreign_key(None, 'daftar_dokumen', 'dokumen', ['dokumen_id'], ['id'])
    op.create_index(op.f('ix_dokumen_id'), 'dokumen', ['id'], unique=False)
    op.drop_constraint(op.f('fk_aktivitas'), 'dokumen', type_='foreignkey')
    op.create_foreign_key(None, 'dokumen', 'aktivitas', ['aktivitas_id'], ['id'])
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.drop_constraint(op.f('teams_ketua_tim_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['ketua_tim_id'], ['id'])
    op.drop_constraint(op.f('user_team_link_team_id_fkey'), 'user_team_link', type_='foreignkey')
    op.drop_constraint(op.f('user_team_link_user_id_fkey'), 'user_team_link', type_='foreignkey')
    op.create_foreign_key(None, 'user_team_link', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'user_team_link', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'user_team_link', type_='foreignkey')
    op.drop_constraint(None, 'user_team_link', type_='foreignkey')
    op.create_foreign_key(op.f('user_team_link_user_id_fkey'), 'user_team_link', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_team_link_team_id_fkey'), 'user_team_link', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_ketua_tim_id_fkey'), 'teams', 'users', ['ketua_tim_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_constraint(None, 'dokumen', type_='foreignkey')
    op.create_foreign_key(op.f('fk_aktivitas'), 'dokumen', 'aktivitas', ['aktivitas_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_dokumen_id'), table_name='dokumen')
    op.drop_constraint(None, 'daftar_dokumen', type_='foreignkey')
    op.drop_constraint(None, 'daftar_dokumen', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dokumen_fisik'), 'daftar_dokumen', 'dokumen', ['dokumen_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_aktivitas'), 'daftar_dokumen', 'aktivitas', ['aktivitas_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_daftar_dokumen_id'), table_name='daftar_dokumen')
    op.drop_constraint(None, 'aktivitas', type_='foreignkey')
    op.drop_constraint(None, 'aktivitas', type_='foreignkey')
    op.create_foreign_key(op.f('aktivitas_team_id_fkey'), 'aktivitas', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('aktivitas_creator_user_id_fkey'), 'aktivitas', 'users', ['creator_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_aktivitas_nama_aktivitas'), table_name='aktivitas')
    op.drop_index(op.f('ix_aktivitas_id'), table_name='aktivitas')
    # ### end Alembic commands ###
