"""Tambahkan Kolom melibatkan_kepala pada tabel aktivitas

Revision ID: d2e3445b854c
Revises: 0c23bea48aa0
Create Date: 2025-09-06 04:14:50.216476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e3445b854c'
down_revision: Union[str, Sequence[str], None] = '0c23bea48aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aktivitas', sa.Column('melibatkan_kepala', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.drop_constraint(op.f('anggota_aktivitas_aktivitas_id_fkey'), 'anggota_aktivitas', type_='foreignkey')
    op.create_foreign_key(None, 'anggota_aktivitas', 'aktivitas', ['aktivitas_id'], ['id'])
    op.alter_column('teams', 'valid_from',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('teams', 'valid_until',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'valid_until',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('teams', 'valid_from',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'anggota_aktivitas', type_='foreignkey')
    op.create_foreign_key(op.f('anggota_aktivitas_aktivitas_id_fkey'), 'anggota_aktivitas', 'aktivitas', ['aktivitas_id'], ['id'], ondelete='CASCADE')
    op.drop_column('aktivitas', 'melibatkan_kepala')
    # ### end Alembic commands ###
